### ISSUE TITLE
Conflict between versions

### ISSUE THREAD

**Issue by Ghits-nl** [GleamTech/VideoUltimate#1]
Hi,
We are using GleamTech DocumentUltimate which use the GleamTech.core.dll version 3.0.0.0.
now we plan to use the VideoUltimate which require GleamTech.core 3.9.5.0.
If I try to upgrade de core dll which is nesecary voor video ultimate then the document ultimate does not work with new core version. should I upgrade both?

**Comment by GleamTech** [comment]
Yes, GleamTech.Core is the common library so you should use the corresponding versions of DocumentUltimate and VideoUltimate. For example, latest NuGet package versions are:

GleamTech.Core       **3.9.6**
VideoUltimate          **1.9.19**
DocumentUltimate   **4.9.6**

If you don't want to update DocumentUltimate then you should install VideoUltimate version which depends on GleamTech.Core version that comes with that DocumentUltimate version. However I recommend using the latest version for all of them.

For reference, this is the version set for GleamTech.Core 3.0.0

GleamTech.Core       **3.0.0**
VideoUltimate          **1.8.0**
DocumentUltimate   **4.0.0**

NuGet feeds:
http://get.gleamtech.com/packages
https://www.nuget.org/profiles/gtdev

**Comment by Ghits-nl** [comment]
Thank you for prompt response!. I'll try the videoultimate version 1.8 and we will upgrade soon.

**Comment by Ghits-nl** [comment]
Is this just a video reader? and not a video player?

**Comment by GleamTech** [comment]
Yes it's a video reader and thumbnailer. We have a web video player in FileUltimate, it only works when you double click a file in FileManager but we may move the web video player as standalone to VideoUltimate in future.
