### ISSUE TITLE
Not supposed japanese title

### ISSUE THREAD

**Issue by futag** [GleamTech/VideoUltimate#2]
What videoultimate not support utf8 or Japanese title file?

**Comment by GleamTech** [comment]
FYI,
Since **Version 2.1.7 - May 22, 2020**
Improved: Unicode file name support for netstandard2.0 DLL (not possible for net40 DLL due to pinvoke restriction, stream can be used instead).

**Comment by GleamTech** [comment]
FYI with **Version 3.3.0 - March 13, 2022** unicode file names are also supported for net461 DLL (but when run on .NET 4.7 runtime)
